steps:
    # Install dependencies
    - name: 'node:18'
      entrypoint: 'npm'
      args: ['ci']

    # Build the Nuxt app
    - name: 'node:18'
      entrypoint: 'npm'
      args: ['run', 'build']

    # Build Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA', '.']

    # Push to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA']

    # Deploy to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [
        'run', 'deploy', 'nuxt-frontend',
        '--image', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000'
      ]