options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'

steps:
  # Install dependencies with caching to speed up builds
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -d "node_modules" ]; then
          echo "Using cached node_modules"
        else
          npm ci
        fi

  # Build the Nuxt app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA', '.']

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'nuxt-frontend',
        '--image', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080'  # يجب أن يطابق EXPOSE و NITRO_PORT في Dockerfile
      ]
