options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'

steps:
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'nuxt-frontend',
      '--image', 'gcr.io/$PROJECT_ID/nuxt-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000'
    ]
